import './components/sliders'
import './components/inputMask'
import './components/customDate'
import './components/validation'
import './components/loginModal'
import './components/regModal'
import './components/passModal'
